---
title: 'xGPhilosophy Tweet Engagement'
# runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    css: custom.css
    orientation: columns
    vertical_layout: scroll
---

```{r setup, include=F, echo=F}
knitr::opts_chunk$set(
  # collapse = TRUE
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)
```

```{r import, include=F}
source('functions.R')
preds <- import_preds()
shap <- import_shap()

if(FALSE) {
df <-
  shap %>%
  nest(shap = -c(stem, idx)) %>%
  # head(5) %>% 
  mutate(
    shap = map(shap, .prep_shap)
  ) %>% 
  select(idx, stem, shap) %>%
  pivot_wider(names_from = stem, values_from = shap, names_glue = '{stem}_shap') %>%
  left_join(preds, by = 'idx')
df
readr::write_rds(df, 'df.rds')
}
df <- readr::read_rds('df.rds')
df
df_long <-
  df %>% 
  select(-retweet_shap) %>% 
  unnest(favorite_shap)
df_long
df_long_key <- df %>% plotly::highlight_key(~text)
preds_key <- preds %>% plotly::highlight_key( ~ text)
# shap_key <- shap %>% plotly::highlight_key(~text, group = 'Select a tweet')
df_key <- df %>% plotly::highlight_key(~text)

plot_time <-
  purrr::partial(
    plot_stem_time,
    # data = preds_key,
    data = df_key,
    width = 475,
    height = 475,
    ... =
  )
plot_pred <-
  purrr::partial(
    plot_stem_pred,
    data = preds_key,
    height = 475,
    width = 475,
    ... =
  )
plot_shap <-
  purrr::partial(
    plot_stem_shap,
    data = df_key,
    height = 475,
    width = 475,
    ... =
  )
```

## Column {data-width="333"}

### Favorites {data-height="333"}

```{r}
plot_time('favorite')
```

### Retweets {data-height="333"}

```{r}
plot_time('retweet')
```

## Column {data-width="333"}

### Favorite Predictions {data-height="500"}

```{r}
# plot_pred('favorite')
plot_stem_pred2(
  data = df_long_key,
  height = 475,
  width = 475,
  stem = 'favorite'
)
```

### Retweet Predictions {data-height="500"}

```{r}
# plot_pred('retweet')
plot_stem_pred(
  data = df_long_key,
  height = 475,
  width = 475,
  stem = 'favorite'
)
```

## Column {data-width="333"}

### Favorite Prediction Explanation {data-height="500"}

```{r}

```

### Retweets Prediction Explanation {data-height="500"}

```{r}
# library(listviewer)
# s <- plotly::schema()
# agg <- s$transforms$aggregate$attributes$aggregations$items$aggregation$func$values
# 
# 
# l = list()
# for (i in 1:length(agg)) {
#   ll = list(method = "restyle",
#             args = list('transforms[0].aggregations[0].func', agg[i]),
#             label = agg[i]) 
#   l[[i]] = ll
# }
# 
# fig <- plot_ly(
#     width = 400,
#   height = 400,
#   type = 'scatter',
#   x = diamonds$cut,
#   y = diamonds$price,
#   mode = 'markers',
#   marker = list(
#     size = 10,
#     color = 'blue',
#     opacity = 0.8
#   ),
#   transforms = list(
#     list(
#       type = 'aggregate',
#       groups = diamonds$cut,
#       aggregations = list(
#         list(
#           target = 'y', func = 'avg', enabled = T
#         )
#       )
#     )
#   )
# )
# fig <- fig %>% layout(
# 
#     title = '<b>Plotly Aggregations</b><br>use dropdown to change aggregation',
#     xaxis = list(title = 'Cut'),
#     yaxis = list(title = 'Price ($)'),
#     updatemenus = list(
#       list(
#         x = 0.25,
#         y = 1.04,
#         xref = 'paper',
#         yref = 'paper',
#         yanchor = 'top',
#         buttons = l
#       )
#     )
#   )
# 
# fig
```
