name: xengagement

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  data-update:
    runs-on: macOS-latest
    env:
      TWITTER_APP: ${{ secrets.TWITTER_APP }}
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install packages
        run: |
          install.packages('remotes')
          remotes::install_github('tonyelhabr/xengagement', dependencies = TRUE, force = FALSE)
          install.packages(c('dplyr', 'tidyr', 'purrr', 'readr'))
        shell: Rscript {0}
         
      - name: Update data
        run: Rscript main.R
        
      - name: Commit results
        run: |
          git commit -m "Updated data" -a || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"